### ISSUE TITLE
META: Improvements to button tap animation

### ISSUE THREAD

**Issue by Jacalz** [fyne-io/fyne#1776]
The initial button tap animation recently landed in develop and it looks great. There are more ways we can improve it and integrate it in more parts of applications. This is a list of tasks ahead of us.

- [ ] Add tap animation for tab container
- [ ] Add tap animation for nodes in Tree
- [ ] Start tap animation from mouse position
- [ ] Adapt to work better for small buttons
![button-tap-small](https://user-images.githubusercontent.com/25466657/104370608-67dfcf00-551f-11eb-960a-f69bde2a8490.gif)
- [ ] Use an elipsis or circle for the animation
![button-tap-circle](https://user-images.githubusercontent.com/25466657/104211705-b2d0e800-5434-11eb-9714-9909ef3861cb.gif)

Possibly more parts it should be integrated?

cc @andydotxyz

**Comment by Extner32** [comment]
Is this in stable now? I like the "circular ripple" animation from the gif more than the "horizontal ripple" animation that we currently have for buttons, tabs,...

**Comment by andydotxyz** [comment]
> Is this in stable now? 

No, If there were updates on this they would be marked on the ticket. The tasks above remain to be done.
