### ISSUE TITLE
3.0: Removal of deprecated APIs

### ISSUE THREAD

**Issue by Jacalz** [fyne-io/fyne#2202]
### Description

This is just a list where can keep track of parts of the API that have been deprecated and should be removed in the upcoming 3.0 release.

- [ ] fyne.NewContainer and  fyne.NewContainerWithLayout() and fyne.NewContainerWithoutLayout().
- [ ] ExtendBaseWidget() on containers.

**Comment by Jacalz** [comment]
FYI, there are a couple deprecation notices missing from this list.

**Comment by stuartmscott** [comment]
Placeholder is one word, yet APIs in Theme (ColorNamePlaceHolder, PlaceHolderColor), Entry (SetPlaceHolder), and Select (PlaceHolder) capitalize the 'h' as if it were two.

**Comment by andydotxyz** [comment]
We will also need to remove:
- [ ] `FileItem.SetSelected()` (originally proposed at #2532) and

**Comment by Jacalz** [comment]
Two more notes:

- We should consider making the `Date` field in DateEntry a `time.Time` and not `*time.Time`.
- Renaming layouts to `layout.NewXYZ` instead of `layout.NewXYZLayout` to avoid stuttering.
