### ISSUE TITLE
Go version upgrade checklist

### ISSUE THREAD

**Issue by Jacalz** [fyne-io/fyne#3242]
### Checklist

- [X] I have searched the [issue tracker](https://github.com/fyne-io/fyne/issues) for open issues that relate to the same feature, before opening a new one.
- [X] This issue only relates to a single feature. I will open new issues for any other features.

### Is your feature request related to a problem?

# Description

Before anyone wonders, I just want to clarify that this ticket is not about saying that we should upgrade the minimum Go versions. Our minimum version supported is still following what is in the latest version of Debian and this issue is not trying change that in any way.

The reason for open it is purely to write down what we can and should improve on when we one day upgrade the minimum Go version. This makes sure that we don't miss anything important. If you notice anything that I have missed, especfially when it comes to using better APIs where available, please update the issue or comment accordingly.

## Go 1.15

- [ ] Remove [work114.go](https://github.com/fyne-io/fyne/blob/master/internal/driver/mobile/gl/work114.go) and remove the build tag for `go115` from `work.go`.
- [ ] Remove any code for 32-bit `darwin` operating systems.
- [ ] Remove any potential code specific to macOS versions before 10.12 Sierra (Sierra is now the minimum).
- [ ] Check usages of `timer.Ticker` to see if we can make use of the `.Reset()` method.

## Go 1.16

- [ ] Remove vendor directory and documentation related to versions without the new module commands (using `install` over `get`).
- [ ] Stop using deprecated `io/ioutil` functions and use the new ones in `io` and `os` instead.
- [ ] Replace `filepath.Walk` usages with faster `filepath.WalkDir`.

## Go 1.17

- [ ] Tidy the module with support for pruned module graphs: `go mod tidy -go=1.17`.
- [ ] Remove all usages of `+build` and only use `go::build`.

## Go 1.18

- [ ] Look at some of the `interface{}` and template generated code to see if generics make sense.
- [ ] Look at usages of [Index](https://tip.golang.org/pkg/strings/#Index), [IndexByte](https://tip.golang.org/pkg/strings/#IndexByte), [IndexRune](https://tip.golang.org/pkg/strings/#IndexRune), and [SplitN](https://tip.golang.org/pkg/strings/#SplitN) and replace with [Cut](https://tip.golang.org/pkg/strings/#Cut) where it makes sense. Similarly applies to `bytes` as well.

## Go 1.19

- [ ] Switch to new atomic types in places where it makes sense.
- [ ] Look at potentially using new functions [Append](https://tip.golang.org/pkg/fmt/#Append), [Appendf](https://tip.golang.org/pkg/fmt/#Appendf), and [Appendln](https://tip.golang.org/pkg/fmt/#Appendln) that append formatted data to byte slices.
- [ ] Stop using the `execabs` package now that it is fixed in the `os/exec` pacakge.

### Is it possible to construct a solution with the existing API?

yes

### Describe the solution you'd like to see.

yes

**Comment by Jacalz** [comment]
I realise that I have missed some more notes about removing potential macOS support code. Will add those another time.

**Comment by andydotxyz** [comment]
Thanks for this. Maybe it would be good to mark any that might be breaking so it can be factored into release plans?

**Comment by Jacalz** [comment]
Good idea. I have updated the information with removed OS support.

**Comment by Jacalz** [comment]
For reference. It looks like we want Go 1.22 as the base if we want to update yuin/goldmark to get much smaller binaries and make wasm-opt be able to handle more aggressive optimisations: https://github.com/WebAssembly/binaryen/issues/7644#issuecomment-2956876721
