### ISSUE TITLE
New threading model

### ISSUE THREAD

**Issue by andydotxyz** [fyne-io/fyne#4654]
### Checklist

- [X] I have searched the [issue tracker](https://github.com/fyne-io/fyne/issues) for open issues that relate to the same feature, before opening a new one.
- [X] This issue only relates to a single feature. I will open new issues for any other features.

### Is your feature request related to a problem?

To work on race conditions and many locking challenges we agreed to revise the threading model (the "App thread").
This issue tracks the work required.

### Describe the solution you'd like to see.

First:
- [x] Back out the BaseWidget.SetFieldsAndRefresh API - it will be obsoleted by "fyne.Go"
- [x] Re-merge draw and event into one thread (#4656)
- [x] Move animation ticks to the main thread (#4656)
- [x] Check that all widget callbacks happen on this same thread (#5384)
- [x] Combine data binding into same thread (and remove test waits) (#5361)
- [x] Add ability to schedule code on the App thread (new "fyne.Go" API #6599)
- [x] Enable race on all our CI test runs (#5384)
- [ ] Add new tests that show that things work as expected from goroutines
- [x] Explicitly document the specific APIs that are still allowed to be called from goroutines without using the above new API. (Possibly only data binding, and various "pure" funcs that don't mutate state?)
- [x] Test on all devices. Now validated on macOS, Linux, Windows, iOS and Android

Then:
- [x] Clean up now-unneeded locks/synchronization in widgets, etc (#5388)
- [x] Revise unit testing to do this all sync and remove waits etc no longer needed (#5384)
- [x] Make the transition less painful for users upgrading to v2.6.0 (#5411)

Also to consider:
~- [ ] Fix issues with re-draw on window resize that led to draw/event separation (moved to next release for new event loop)~
- [ ] Consider adding a `noCopy` struct that is a dummy implementation of `sync.Locker` to BaseWidget so `go vet` can still complain about passing widgets by value (#5520)

**Comment by andydotxyz** [comment]
> > Re-merge draw and event into one thread
> 
> This might be the easiest path, but it isn't necessarily the only one. We can keep them on separate threads as long as we have them lock when reading or writing state.

Yes, there could be locking based solutions - but part of this is trying to find the simplest solution, so reverting the thread split seems like a good start.

**Comment by andydotxyz** [comment]
Work is begun on this - I updated the TODO above to highlight what is needed in the order.
I have a proof of concept for most of the top list working locally and it is indeed race-free but with a significant lag on heavy event usage... more work to do before I open more PRs

**Comment by Jacalz** [comment]
The no copy idea might be easily solved with this Go proposal once accepted: https://github.com/golang/go/issues/70811
